#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sshfs
Version  : 3.3.2
Release  : 14
URL      : https://github.com/libfuse/sshfs/archive/sshfs-3.3.2.tar.gz
Source0  : https://github.com/libfuse/sshfs/archive/sshfs-3.3.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: sshfs-bin
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(fuse3)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : python3

%description
SSHFS
=====
About
-----
SSHFS allows you to mount a remote filesystem using SFTP. Most SSH
servers support and enable this SFTP access by default, so SSHFS is
very simple to use - there's nothing to do on the server-side.

%package bin
Summary: bin components for the sshfs package.
Group: Binaries

%description bin
bin components for the sshfs package.


%prep
%setup -q -n sshfs-sshfs-3.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525044793
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sshfs
/usr/sbin/mount.fuse.sshfs
/usr/sbin/mount.sshfs
