#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sshfs
Version  : 3.4.0
Release  : 17
URL      : https://github.com/libfuse/sshfs/releases/download/sshfs-3.4.0/sshfs-3.4.0.tar.xz
Source0  : https://github.com/libfuse/sshfs/releases/download/sshfs-3.4.0/sshfs-3.4.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: sshfs-bin
Requires: sshfs-license
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(fuse3)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : python3

%description
SSHFS
=====
About
-----
SSHFS allows you to mount a remote filesystem using SFTP. Most SSH
servers support and enable this SFTP access by default, so SSHFS is
very simple to use - there's nothing to do on the server-side.

%package bin
Summary: bin components for the sshfs package.
Group: Binaries
Requires: sshfs-license

%description bin
bin components for the sshfs package.


%package license
Summary: license components for the sshfs package.
Group: Default

%description license
license components for the sshfs package.


%prep
%setup -q -n sshfs-3.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530274444
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/doc/sshfs
cp COPYING %{buildroot}/usr/share/doc/sshfs/COPYING
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sshfs
/usr/sbin/mount.fuse.sshfs
/usr/sbin/mount.sshfs

%files license
%defattr(-,root,root,-)
/usr/share/doc/sshfs/COPYING
